// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkVT2seiJ42U-xXdmjFKYoQspN3A916Y',
    appId: '1:40075742974:web:318ec6b413fe2758dc5faf',
    messagingSenderId: '40075742974',
    projectId: 'g0-planner',
    authDomain: 'g0-planner.firebaseapp.com',
    storageBucket: 'g0-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfx8d3V9lBFAe66WdLtKm6O07a-UTfQnc',
    appId: '1:40075742974:android:95fc691c586ee6d0dc5faf',
    messagingSenderId: '40075742974',
    projectId: 'g0-planner',
    storageBucket: 'g0-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPZbmw83pvvyQIRDK1HYBXsKS6qTGAKr0',
    appId: '1:40075742974:ios:6afa7495840db6a6dc5faf',
    messagingSenderId: '40075742974',
    projectId: 'g0-planner',
    storageBucket: 'g0-planner.firebasestorage.app',
    iosClientId: '40075742974-o110kg966olr9454ep7rbpoc6g3d8omq.apps.googleusercontent.com',
    iosBundleId: 'com.example.goPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPZbmw83pvvyQIRDK1HYBXsKS6qTGAKr0',
    appId: '1:40075742974:ios:6afa7495840db6a6dc5faf',
    messagingSenderId: '40075742974',
    projectId: 'g0-planner',
    storageBucket: 'g0-planner.firebasestorage.app',
    iosClientId: '40075742974-o110kg966olr9454ep7rbpoc6g3d8omq.apps.googleusercontent.com',
    iosBundleId: 'com.example.goPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbkVT2seiJ42U-xXdmjFKYoQspN3A916Y',
    appId: '1:40075742974:web:785cfc523b0be4f3dc5faf',
    messagingSenderId: '40075742974',
    projectId: 'g0-planner',
    authDomain: 'g0-planner.firebaseapp.com',
    storageBucket: 'g0-planner.firebasestorage.app',
  );

}